name: Validate JSON and CSV Files

on:
  pull_request:
    branches:
      - main

jobs:
  validate-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl pyyaml

      - name: Validate JSON and CSV files
        run: |
          python scripts/scripts_validate_files.py
        env:
          METRIC_CONFIG_PATH: /INPUT/03_METADATA_FILES/METRIC_SEGMENT_ASSET/CONFIG_FILE/Metric_Config_File.csv
          MASTER_CONFIG_PATH: /INPUT/03_METADATA_FILES/METRIC_SEGMENT_ASSET/CONFIG_FILE/Master_Config_File.csv
          OUTPUT_PATH: /work/output/dqm_report.xlsx

      - name: Trim spaces in Metric_config_file.csv
        run: |
          python scripts/trim_spaces.py
        env:
          METRIC_CONFIG_PATH: /INPUT/03_METADATA_FILES/METRIC_SEGMENT_ASSET/CONFIG_FILE/METRIC_CONFIG.File.csv
